### ISSUE TITLE
 Error when editing published articles leads to error page instead of the edited page

### ISSUE THREAD

**Issue by rohan472000** [Hashnode/support#70]
**Description:**
I have encountered a bug on the Hashnode platform related to editing published articles. When I attempt to edit a previously published article, after editing instead of being directed to the edited page, I am redirected to an error page.

**Steps to Reproduce:**

- Log in to the Hashnode platform.
- Go to your published articles section.
- Select one of the published articles you want to edit.
- Click on the edit button or the edit option associated with the article, edit something in it.
- Instead of being directed to the edited page, an error page is displayed.

**Expected Behavior:**
After editing a published article, I expect to be directed to the edited page where I can see the changes.

**Actual Behavior:**
Instead of being directed to the edited page, I am redirected to an error page, which prevents me from seeing changes made to the article.
screenshot : 
![Screenshot (221)](https://github.com/Hashnode/hashnode-cli/assets/96521078/fc6ccc9d-0d3e-4232-99ab-3b27163bec2c)

**Additional Information:**

- This issue occurs consistently every time I attempt to edit a published article.
- I have tried clearing my browser cache and using different browsers, but the issue persists.
- Other functionalities of the Hashnode platform are working correctly; this issue seems to be specific to editing published articles.

**Comment by lakbychance** [comment]
Hey @rohan472000 Thanks for reporting this. This might be due to incorrect domain mapping but nevertheless we are fixing it to redirect to the default `rohan-anand.hashnode.dev` url. You can meanwhile preview your post at that url.

**Comment by lakbychance** [comment]
Hey @rohan472000 now you should get redirected at the correct destination ( `*.hashnode.dev` subdomain until your domain is properly configured ). If you're wondering why `rohan-anand.com` is not still getting redirected to, it might be due to missing steps in domain mapping. You can check out the steps here -> https://support.hashnode.com/en/articles/5755362-how-to-map-a-custom-domain. If your domain mapping was previously working, please check if your domain is not expired. if none of the above work for you regarding the domain stuff, reach out to our support on [Discord](https://discord.com/channels/578864970696097812/579989537317715979)

**Comment by rohan472000** [comment]
@lakbychance , Thanks for the quick action, yes It is now working as expected.
